title: OCR Scheduler
description: This is an updated simple test add-on
instructions: This is a sample instruction.
type: object
documents: []
properties:
  ocr_engine:
    title: OCR Engine
    type: string
    enum:
      - azure
      - google
      - doctr
  batch_size:
    title: 'Batch size'
    type: integer
    default: 25
    description: "How many documents do you want OCR'd per scheduled run?"
  project_id:
    title: "Project ID"
    type: integer
    description: "Project ID of the project you would like to run this on." 
  to_tag:
    title: "Tag OCR'd documents?"
    type: boolean
    description: "If selected, the key/value pair of ocr_engine:azure will be added to the document as metadata"
required:
  - batch_size
  - project_id
  - ocr_engine
eventOptions:
  name: ocr_scheduler
  events:
    - hourly
    - daily
    - weekly
categories: 
  - premium
version: 2
